### ISSUE TITLE
Release new "SynapsePy" version with the latest fixes

### ISSUE THREAD

**Issue by myartsev** [SynapseFI/SynapsePy#18]
Latest release appears to be `1.2.8` and SynapsePy is now up to `1.2.11`

**Comment by kam193** [comment]
Hi, 
I think it's kind of important thing. @thewalrusmaximus @sankaet you are last contributors from Synapse company, is there any possibility to release a new version to pypi?

**Comment by sankaet** [comment]
Hi both, checking internally to ensure that we have the latest version live.

**Comment by thewalrusmaximus** [comment]
Live SynapsePy release updated to 1.2.11
