### ISSUE TITLE
locate_atms() method: missing "lon" parameter in signature

### ISSUE THREAD

**Issue by m-vdb** [SynapseFI/SynapsePy#3]
Although it is present in function docstring:
https://github.com/SynapseFI/SynapsePy/blob/23c9d0740d680c54aabcfdbc0ba8ec8091d79981/synapsepy/client.py#L216-L237

**Comment by mattbernardo** [comment]
Thanks!
This has been fixed in v1.2.4 and pushed. Please pull the latest version.
