### ISSUE TITLE
Get an error when user oauth returns an error response

### ISSUE THREAD

**Issue by di2pro** [SynapseFI/SynapsePy#7]
Python 3.6
> app_1  |   File "/usr/local/lib/python3.6/site-packages/synapsepy/user.py", line 58, in oauth
app_1  |     response = self.http.post(path, body)
app_1  |   File "/usr/local/lib/python3.6/site-packages/synapsepy/http_client.py", line 105, in post
app_1  |     return self.parse_response(response)
app_1  |   File "/usr/local/lib/python3.6/site-packages/synapsepy/http_client.py", line 152, in parse_response
app_1  |     raise api_errors.ErrorFactory.from_response(payload) from e
app_1  | UnboundLocalError: local variable 'e' referenced before assignment

**Comment by Sousa5** [comment]
@mattbernardo Same here.

**Comment by mattbernardo** [comment]
Sorry about that, fixed in v1.2.5 please pull the latest @Sousa5 @di2pro
